### ISSUE TITLE
Dbus & nodejs issues

### ISSUE THREAD

**Issue by kaccha** [diederikfeilzer/node-omx-interface#6]
Thanks for the simple & effective dbus + nodejs  app. I'm currently using your code with few changes for my project. Its better i report them so that more can people can use your project.

Caching problem (index.js)
1. The variable cache fail to rest to the default values because when defined  
var cache = default; it actually keep the reference to the original obj, so when you recall cache=default to rest the values it fails. I found various solution like object clone but want to avoid using additional module to keep the code base small.

My quick solution 
```
function setDefault ()
{
	var defaults = {
		path:{
			value:'',
			time:new Date(),
			valid:false
		},
		position:{
			value:false,
			time:new Date(),
			valid:false
		},
		duration:{
			value:0,
			time:new Date(),
			valid:false
		},
		volume:{
			value:0,
			time:new Date(),
			valid:false
		},
		isPlaying:{
			value:0,
			time:new Date(),
			valid:false
		}
	  };
		
		return defaults;
		
}

var cache = setDefault();
```

2. set volume fails typo error line 174 	
`	if(error && setPositionTryCount < 4){`

chages		
`if(error && (setVolumeTryCount < 4)){
`
Also I have to change the bus.sh 
```
set volume
  dbus-send --print-reply=double --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Volume double:$2

```

To

`  dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Volume double:$2 >/dev/null
`

**Comment by diederikfeilzer** [comment]
Thanks for the input. I've changed it. Including some other much needed changes.
